#include <stdio.h>
#include "main.h"

/**
* *_memset -  fills memory with a constant byte
*@s : pointer to a memory zone
*@b : bytes used to fill memory
*@n : number of bytes to fill
* Return: array generated by our function
*/
char *_memset(char *s, char b, unsigned int n)
{
unsigned int i;
for (i = 0; i < n; i++)
{
s[i] = b;
}
return (s);
}
